import { useNavigate } from "react-router-dom";
import { Receipt, Eye, Calendar, DollarSign } from "lucide-react";
import { useInvoices } from "@/hooks/useInvoices";
import { cn, formatDate } from "@/utils";

export default function ClientInvoicesPage() {
  const navigate = useNavigate();
  const { data: invoices, isLoading } = useInvoices();

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  const getStatusBadge = (status: string) => {
    switch (status) {
      case "paid":
        return "bg-emerald-50 text-emerald-700 border-emerald-100";
      case "sent":
        return "bg-blue-50 text-blue-700 border-blue-100";
      case "overdue":
        return "bg-rose-50 text-rose-700 border-rose-100 font-bold";
      default:
        return "bg-slate-50 text-slate-500 border-slate-200";
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="text-left">
        <h1 className="text-2xl font-black tracking-tight text-slate-800">My Invoices</h1>
        <p className="text-xs font-semibold text-slate-400 mt-0.5">View and monitor bills and receipts.</p>
      </div>

      {invoices && invoices.length > 0 ? (
        <div className="bg-white border border-slate-200 rounded-3xl shadow-sm overflow-hidden text-left">
          <table className="w-full text-left text-xs font-semibold">
            <thead>
              <tr className="border-b border-slate-200 bg-slate-50/50 text-slate-400">
                <th className="px-5 py-3.5">Invoice #</th>
                <th className="px-5 py-3.5">Associated Project</th>
                <th className="px-5 py-3.5">Due Date</th>
                <th className="px-5 py-3.5">Amount</th>
                <th className="px-5 py-3.5">Status</th>
                <th className="px-5 py-3.5 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-slate-700 font-medium">
              {invoices.map((inv) => (
                <tr key={inv.id} className="hover:bg-slate-50/20 transition-colors">
                  <td className="px-5 py-4 font-extrabold text-slate-850">
                    {inv.invoice_number}
                  </td>
                  <td className="px-5 py-4 text-slate-500 font-semibold truncate max-w-[200px]">
                    {inv.project?.name || "—"}
                  </td>
                  <td className="px-5 py-4 flex items-center gap-1.5 text-slate-400">
                    <Calendar size={12} />
                    <span>{inv.due_date ? formatDate(inv.due_date) : "—"}</span>
                  </td>
                  <td className="px-5 py-4 font-black text-slate-800">
                    ₹{inv.amount.toLocaleString("en-IN")}
                  </td>
                  <td className="px-5 py-4">
                    <span className={cn(
                      "px-2.5 py-0.5 rounded-full text-[9px] font-black uppercase border tracking-wider",
                      getStatusBadge(inv.status)
                    )}>
                      {inv.status}
                    </span>
                  </td>
                  <td className="px-5 py-4 text-right">
                    <button
                      onClick={() => navigate(`/invoices/${inv.id}`)}
                      className="inline-flex items-center gap-1 px-3 py-1.5 border border-slate-250 hover:bg-slate-50 text-slate-700 text-[10px] font-bold rounded-xl transition-all"
                    >
                      <Eye size={12} />
                      View Invoice
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <div className="text-center py-20 bg-white border border-slate-200 rounded-3xl max-w-md mx-auto">
          <Receipt size={48} className="mx-auto text-primary mb-4" />
          <h3 className="text-base font-bold text-slate-800 mb-1">No Invoices Yet</h3>
          <p className="text-xs text-slate-400 max-w-xs mx-auto leading-relaxed">
            Your billing invoices and statements will appear here once generated by the finance team.
          </p>
        </div>
      )}
    </div>
  );
}
